### ISSUE TITLE
[login,register] 로그인, 회원가입 기능 API

### ISSUE THREAD

**Issue by hoonloper** [modern-agile-team/3term-mini-back#11]
💡 로그인 API 3기

## 목차
1.로그인 API

2.회원가입 API

3.약관동의 API

## **1.로그인 API**

> URL: moae/user/login 
> 
> 
> METHOD: POST
> 
>

### **Request**
- **Content-Type:** `application/json; charset=utf-8`
```json
{
    "id" : "string",
    "password" : "string"
} 
```
예시 : (테스트 이걸로 고고고)
```json
{
    "id" : "subro",
    "password" : "1023"
} 
```

데이터를 보내 주었을 때에 대한 응답
Response

### **Success**

- **Status:** `201 Create`
- **Content-Type:** `application/json; charset=utf-8`

로그인이 성공한 경우
```json
{
    "success" : "true",
    "msg" : "로그인 성공."
}
```
### **Fail**

- **Status:** `401 Bad Request`
- **Content-Type:** `application/json; charset=utf-8`

비밀번호가 틀린 경우 
```json
{
    "success" : "false",
    "msg" : "비밀번호가 틀렸습니다"
}
```

아이디가 없는 경우
```json
{ 
    "success" : "false" , 
    "msg" : "존재하지 않는 아이디입니다." 
}
```

## **2.회원가입 API**

> URL: moae/user/register 
> 
> 
> METHOD: POST
> 
>

### **Request**
- **Content-Type:** `application/json; charset=utf-8`
```json
{
    "id" : "string(필수,중복불가)",
    "password" : "string(필수)",
    "passwordConfirm" : "string",
    "mail" : "string(중복불가)",
    "name" : "string(필수)", 
    "nickname" : "string(중복불가)",
    "year" : "int",
    "school" : "int"
} 
```
![image](https://user-images.githubusercontent.com/86092785/152928905-e7f74a8e-3867-486d-9224-8940bb69c55f.png)
![image](https://user-images.githubusercontent.com/86092785/152928954-3f92206f-f87a-409a-8b34-8ea1dbaf8543.png)

예시 :  (테스트 이걸로 고고 id,nickname,mail 중복되었다고 나오면 성공)
```json
{
    "id" : "subro",
    "password" : "1023",
    "mail" : "clark9810@naer.com",
    "nickname" : "수브로",
    "year" : "3",
    "school" : "1"
} 
```

데이터를 보내 주었을 때에 대한 응답
Response

### **Success**

- **Status:** `201 Create`
- **Content-Type:** `application/json; charset=utf-8`

```json
{
   "success" :  "true" ,
   "msg" : "회원가입이 정상적으로 수행되었습니다."
} 
```

### **Fail**

- **Status:** `401 Bad Request`
- **Content-Type:** `application/json; charset=utf-8`

필수 정보를 보내주지 않았을 때

```json
{
   "success" :  "false" ,
   "msg" : "(보내주지 않은 정보)에 해당하는 값을 입력해 주세요"
} 
```

비밀번호와 비밀번호 확인이 서로 다를 때
```json
{
    "success" : "false",
    "msg" : "비밀번호와 비밀번호 확인이 서로 다릅니다."   
} 
```

아이디,닉네임,이메일이 중복된 사용자가 이미 있을 때
```json
{
    "success" : "false",
    "msg" : "(중복된 값)는 중복된 값입니다.."   
} 
```

## **3.약관동의 API**

>URL : moae/user/agreement
>
>
> METHOD: POST
>
>

### **Request**
- **Content-Type:** `application/json; charset=utf-8`
```javascript
{
    "id": string,
    "0": true,
    "1": true,
    "2": true,
    "3": true/false,
    "4": true,
    "5": true
}
```

### **Success**
- **Status:** `201 POST`
- **Content-Type:** `application/json; charset=utf-8`

약관동의 정보가 정상적으로 담긴 경우

```json
{
   "success" : "true" ,
    "msg" : "약관동의가 정상적으로 등록되었습니다."
}
```

### **Fail**

- **Status:** `401 Bad Request`
- **Content-Type:** `application/json; charset=utf-8`

```json
{
    "success" : "false",
    "msg" : "약관동의가 등록되지 않았습니다."
}
```
### **Fail**
서버의 코드가 잘못되었거나, 서버 자체에 에러가 났을 경우
- **Status:** `500 Server Error`
- **Content-Type:** `application/json; charset=utf-8`

```javascript
{
   msg: "약관동의 오류 입니다. 서버 개발자에게 문의하세요."
}
```

**Comment by SuBroooo** [comment]
💡 로그인 API 3기

1. 로그인  API
URL: /login 예시 : /login

METHOD: POST

Request
Content-Type: application/json; charset=utf-8
{
    "id" : "string",
    "password" : "number && string"
} 
예시 :
{
    "id" : "subro",
    "password" : "1023"
} 

데이터를 보내 주었을 때에 대한 응답
Response

Success
Status: 201 Create
Content-Type: application/json; charset=utf-8

로그인이 성공한 경우
{
    "success" : "true",
    "msg" : "로그인 성공."
}

Fail
Status: 401 Bad Request
Content-Type: application/json; charset=utf-8
비밀번호가 틀린 경우 
{
    "success" : "false",
    "msg" : "비밀번호가 틀렸습니다"
}

아이디가 없는 경우
{ 
    "success" : "false" , 
    "msg" : "존재하지 않는 아이디입니다." 
}
